### ISSUE TITLE
Switch off links to all external websites but keep links to Choices

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#12]
any links to external websites/private to be switched off/removed

**Comment by dogtanian28** [comment]
patient information leaflets still seem to be from Patient.co.uk when you click on the i icon for problems on the record pages. are these going to be removed or hidden?

**Comment by ballzy** [comment]
@Seahermit @dogtanian28 I don't think that this is fixed yet

**Comment by Seahermit** [comment]
Is now!

**Comment by dogtanian28** [comment]
from conditions and drugs on test patient this looks like it is closed, but we cannot test for all condtions so assume EGL have done this. on that note this issue is closed by PO
