### ISSUE TITLE
Change OSU account creation page to ask for practice level information so only those users at a pilot site can access it

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#14]
Technically how do we stop people who are not a part of the pilot from accessing this EGL NHS site?

Agreed to request practice level information when a user tries to create an OSU account.

**Comment by ballzy** [comment]
@Saf456 @dogtanian28 how do we test this?

**Comment by Seahermit** [comment]
On creating a new account you need to put in a practice ID, which you can currently use TESt01 or A12345

**Comment by dogtanian28** [comment]
done
