### ISSUE TITLE
Update Print Summary styles

### ISSUE THREAD

**Issue by ballzy** [AscentMS/NHSD#15]

**Comment by ballzy** [comment]
Ben, please can you add the following rules to your print.css

body {font-family: arial;}

th { background: #ebebeb; }
tr.sub-header td { background: #ebebeb; }
div.print-label-warning { background-color: #FFB81C; }

**Comment by ballzy** [comment]
Over to you Ben

**Comment by ballzy** [comment]
Any comment on this @Seahermit ?
I was just wondering why it hasn't moved for a while - ta

**Comment by Seahermit** [comment]
Oops! Sorry, missed the css you inserted, will be in the update today.

Sorry!

**Comment by ballzy** [comment]
Sorry, that yellow looks awful.

div.print-label-warning { background-color: #005EB8; }
img { margin: 20px 0px 15px 0px; }

**Comment by dogtanian28** [comment]
reviewed with Chris that this change is as asked. So as PO i am closing issue down
