### ISSUE TITLE
Appointments page - repeating background image

### ISSUE THREAD

**Issue by ballzy** [AscentMS/NHSD#22]
I can't seem to fix this. It's on the page where you select which appointment time you are attending. I also can't recreate it locally

**Comment by Seahermit** [comment]
Where is this?  Any chance of a screen shot?

**Comment by ballzy** [comment]
![repeat-image](https://user-images.githubusercontent.com/4947363/27279418-798a9182-54dc-11e7-9a38-75ea6f736cfb.jpg)

**Comment by ballzy** [comment]
thanks
