### ISSUE TITLE
Pop up linking to EGL app on mobile login screen 

### ISSUE THREAD

**Issue by dogtanian28** [AscentMS/NHSD#26]
When loading the login screen for our version of EGL a pop up appears stating that an app exists. The app is out of scope for this project so can this be removed ? ![](http://i.imgur.com/6u49oOQ.jpg)

**Comment by ballzy** [comment]
Stewart, can you test this please?

**Comment by dogtanian28** [comment]
Confirm no longer pop up. Can be closed
