### ISSUE TITLE
Print link - consider changing this to download

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#28]
As our commitment is access and download, do we need the print link to say download

**Comment by ballzy** [comment]
@saf456 I personally don't think that this is neccessary. The 'Print' feature is to let you print the summary after all.
You can Export the XML which is more like "Download" however is isn't really download.
@dogtanian28 I suggest that you have the final say on this

**Comment by dogtanian28** [comment]
Can we call it print/Download

**Comment by ballzy** [comment]
@Seahermit Is it possible to Change the "Print" link to read "Print/download"?
If so then please change it - thanks

**Comment by ballzy** [comment]
That's great Ben. For some reason the link has turned green in the process though

**Comment by dogtanian28** [comment]
confirmed text change, so as PO am ok to close issue
