### ISSUE TITLE
Feasibility of having an exit survey - whats impact?

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#29]
Where can an exit survey sit ? On EGL after logout screen or do we direct back to NHS.UK

**Comment by Seahermit** [comment]
I would suggest directing back to NHS.uk if possible - I can add in a pop-up or something to do this, but it would be difficult to change after launch due to the change control process...

**Comment by Saf456** [comment]
@gordonss could you map this out with Tero?

**Comment by dogtanian28** [comment]
not going down this route, so this issue can be closed
