### ISSUE TITLE
Name of product to be changed - GP Online Services

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#30]
Following discussions with SRO, the name of the product EGL needs to be changed on all pages where this is seen (mostly help pages and information pages)

**Comment by ballzy** [comment]
@dogtanian28 do we have a name yet?

**Comment by dogtanian28** [comment]
i think that we should be factual rather than catchy. so i would be happy with something like "GP Online Services"

**Comment by ballzy** [comment]
Ben, are you able to easily replace Evergreen Life with "GP Online Services" wherever it appears on the website?

**Comment by Seahermit** [comment]
Yep, I'm about halfway through, will have that completed today I think

**Comment by ballzy** [comment]
Just noticed the Password reset pages need the name changing on them @Seahermit - ta

**Comment by ballzy** [comment]
I am going to assume that this is complete. Any other instances should be picked up by our review
