### ISSUE TITLE
Help page - remove references to Evergreen Life

### ISSUE THREAD

**Issue by ballzy** [AscentMS/NHSD#32]

**Comment by dogtanian28** [comment]
i am getting an intermittent issue whereby sometimes i still see the egl app part of the help page
see word file for screenshots
[help pg issue.docx](https://github.com/AscentMS/NHSD/files/1105457/help.pg.issue.docx)

**Comment by dogtanian28** [comment]
moved comment to #33 

this one is reviewed and closed
