### ISSUE TITLE
Appointments page - CSS issues when you have selected an appointment

### ISSUE THREAD

**Issue by ballzy** [AscentMS/NHSD#34]

**Comment by ballzy** [comment]
div.appointments div.appointment.selected .detail h4 { background-image: none; }
div.appointments div.appointment.selected .detail div.date { background-image: none; padding-left: 0;}
div.appointments div.appointment.selected .detail .location { background-image: none; }
div.appointments div.appointment.selected .telephone h4 { background-image: none; }
div.appointments div.appointment.selected .reason h4 { background-image: none; }

@Seahermit please add these styles to the css - thanks

**Comment by ballzy** [comment]
The CSS is in there but there are more issues with this page.
So I will add a comment in below this comment with more CSS in it to try and fix the page.

**Comment by ballzy** [comment]
div.appointments div.appointment.selected .detail div.date { padding-left: 10px; }
div.appointments div.appointment.selected .detail .location { padding-left: 10px; }
div.appointments div.appointment.selected .detail .session { padding-left: 10px; }
div.appointments div.appointment.selected div.vertical-line { border-right: 0; }
div.appointments div.appointment span.gp, div.appointments div.appointment span.gp:not(.selected), div.appointments div.appointment span.gp:not(.error):not(#Appointments .empty):not(#Appointments .empty) { display: block; background-image: none; }
#timeout-content button#ButtonTimeoutStay:hover, div#UserWarning div.content button:hover { background-color: #fff; }
div.appointments div.appointment.selected .detail .gp span { padding-right: 5px; color: #000; }
div.appointments div.appointment.selected .reason div { padding: 5px; }
div.appointments div.appointment.selected .reason input { padding-left: 5px; width: 70%; margin-top: 0; }

**Comment by dogtanian28** [comment]
chiris, is the following issue with a green button already part of the above work ?
![book appointment button](https://user-images.githubusercontent.com/29567457/27594988-48572a08-5b53-11e7-8455-2302b5355644.PNG)

**Comment by ballzy** [comment]
No it's not. I'll have a look

**Comment by ballzy** [comment]
div.appointments div.appointment.selected button.app-book { background-color: #005EB8; }

should fix it

**Comment by dogtanian28** [comment]
reviewed on Chrome, Edge and IE11 - although IE doesnt seem to show logos as big, all issues seem to have been fixed so as PO i close the issue
