### ISSUE TITLE
Design forgotten password pages (4)

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#35]

**Comment by ballzy** [comment]
One this I have notice. Would it be possible @Seahermit to have the re-type password field and label on the next line. This appears on page 4 of the Forgotten Password route - ta

**Comment by Seahermit** [comment]
I'm not sure I understand this - they're labels & divs, you should be able to just stick 'em wherever you want, or have I missed something?

**Comment by ballzy** [comment]
Please add the following CSS to the stylesheet.

div#TablePassword.account { width: 70%; }

**Comment by ballzy** [comment]
I can't test this as the Forgotten Password flow isn't sending out Security Codes
