### ISSUE TITLE
No HTML <TITLE> on pages

### ISSUE THREAD

**Issue by gordonss** [AscentMS/NHSD#37]
Good practice to have a HTML.HEAD.TITLE on every page. It's used as bookmark suggestion by most browsers too

**Comment by Seahermit** [comment]
Weird, seems empty on some pages.  Will fix.

**Comment by ballzy** [comment]
Not sure where to check this @gordonss could you have a look?

**Comment by gordonss** [comment]
I've clicked-through and it looks like this is now resolved

**Comment by dogtanian28** [comment]
help page still references EGL

**Comment by dogtanian28** [comment]
reviewed help page and now does not reference EGL so as PO i close this issue
