### ISSUE TITLE
My prescriptions, Settings and Help buttons not working on mobile

### ISSUE THREAD

**Issue by dogtanian28** [AscentMS/NHSD#39]
i am not sure if this is because this is wip but on both android and IOS browsers, the "my prescriptions, Settings and Help" buttons are not actually buttons and do not allow a user to do anything.

**Comment by dogtanian28** [comment]
![](http://i.imgur.com/nCa7yap.jpg)

**Comment by ballzy** [comment]
@Seahermit this will be solves by the new hamburger mobile menu that we discussed a moment ago - ta

**Comment by dogtanian28** [comment]
![](http://i.imgur.com/uxcAHk2.jpg)

**Comment by dogtanian28** [comment]
This is how it now looks on chrome on android/chrome and iOS/safari

**Comment by Seahermit** [comment]
Yeah... still working on it :(. But at least the Security message fits on the screen now!

**Comment by dogtanian28** [comment]
ben thanks, understand its WIP. just doing a review of each current github thats all and closing quite a few.

**Comment by Seahermit** [comment]
Is working now, and is awesome.

**Comment by dogtanian28** [comment]
Ben, looks a lot better on mobile thanks,

Couple of comments, main one being, hamburger menu has a top level name of My Record when it should probably just say something like Menu. is this possible?

other comments are that on a browser, when resizing down, sometimes things go a bit iffy, i dont think this is an issue for  our pilot as it works on a full browser and also on mobile, but could have an issue on some smaller screens but the numbers wont be high so i dont need it changing, just a highlight. screenshots can be provided if needed

**Comment by Seahermit** [comment]
Ah, I got a bit too clever it seems - it should change to whatever you are looking at. I can change it to just "Menu"

The resizing thing I know about, but haven't worked out - seems a combination of the css and JavaScript resizing not firing completely properly

**Comment by dogtanian28** [comment]
I think for most sizes of devices this should be ok for now.

**Comment by Saf456** [comment]
now showing just menu. PO checked and can close
