### ISSUE TITLE
green text on appointment booking

### ISSUE THREAD

**Issue by dogtanian28** [AscentMS/NHSD#40]
when filtering appointments on doctor or location, this text is still in green

![green appts text](https://user-images.githubusercontent.com/29567457/27594846-d923de38-5b52-11e7-8a64-06a94f559152.PNG)

**Comment by ballzy** [comment]
@Seahermit please add:
div.appointments #Filters .filter-add { color: #005EB8; }

**Comment by dogtanian28** [comment]
confirmed as changed, As PO i close this issue.
