### ISSUE TITLE
EGL logo too large on mobile so covers other links

### ISSUE THREAD

**Issue by dogtanian28** [AscentMS/NHSD#41]
when on mobile the new EGL logo is too large and interacts with other items in the bottom blue bar. could this logo be reduced in size. it is also a lot larger than NHS logo on site so looks out of place on NHS site.

**Comment by dogtanian28** [comment]
![](http://i.imgur.com/WYwJYtr.jpg)

**Comment by dogtanian28** [comment]
Ben, still having issue on an iphone 5s using chrome test this morning after your changes, it seems the logo ins't responsive on that. 
![img_3188](https://user-images.githubusercontent.com/29567457/27624939-b4063cd0-5bda-11e7-85aa-06e969abebdf.PNG)


i think we need a call with rob/lachlan on logos as we can;t have the changes made at the top. i will send an email invite out for this week.

**Comment by Seahermit** [comment]
Well that's annoying!  But for the changes at the top - yes, people need to talk about that.  It was a bit late when I did that, so didn't manage to send the message that this was a starting point for discussion.  So discussion to happen :)

**Comment by dogtanian28** [comment]
reviewed on chrome on android and Safari on IOS, although logo seems slightly different on each. it no longer interferes with the text so as PO i am closing this issue
