### ISSUE TITLE
My Appointments page has colliding text on Firefox/chrome

### ISSUE THREAD

**Issue by gordonss** [AscentMS/NHSD#43]
The appointments text is jumbled on Firefox
I have Firefox 45.4.0
![myapptsbug](https://user-images.githubusercontent.com/9844165/27688391-5b2c740a-5cd2-11e7-8ef6-ebfc6983b9cb.png)

**Comment by ballzy** [comment]
@Seahermit for some reason the following style isn't being picked up in Chrome/Firefox. but it works in Safari. Any ideas. It is on the view Appointments page

div.appointments div.appointment:not(.selected) span:not(.error):not(#Appointments .empty), div.appointments div.appointment:not(.selected) td {padding: 0.5em 0em 0.5em 2em; }

**Comment by Seahermit** [comment]
Weird Safari works but not Chrome!  Firefox I can understand...

I'll have a look

**Comment by dogtanian28** [comment]
have reviewed on Chrome/IE/EDGE and as PO i am ok to close issue
