### ISSUE TITLE
HIGH PRIORITY: New prescription ordered but doesn't appear on the list of prescriptions

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#49]
On the Prescriptions page I ordered 'Aspirin' successfully but this did not appear on the list of prescriptions

**Comment by Seahermit** [comment]
This is a bit dependant on which clinical system you are connected to.  Emis Web this works fine for everything we've tested, TPP makes the order disappear and only shows in your medical record.

If you're linked to the internal test site (Site TEST01) then it probably won't turn up as it's not actually ordering it internally.

So... Is this linked against a real Emis Web site (or the test site)?

**Comment by Saf456** [comment]
@gordonss  one for Andrew to test please - he's not in github yet

**Comment by Saf456** [comment]
Andrew to test with real test site @gordonss

**Comment by andrewleponis** [comment]
HI.  I've tested the new functionality.  You can now order a repeat prescription. However there is no limit to the number you can order.

![image](https://user-images.githubusercontent.com/29251985/28204437-dadb781e-6875-11e7-9449-a3939971c4e2.png)
