### ISSUE TITLE
Generate NHS Favicon

### ISSUE THREAD

**Issue by ballzy** [AscentMS/NHSD#5]
I think I will have to have a see what we have here already

**Comment by ballzy** [comment]
![favicon](https://user-images.githubusercontent.com/4947363/27091821-32f74af8-5059-11e7-8284-4c5375152f99.png)

**Comment by Seahermit** [comment]
Loads of favicons for the whole extended batch now exist - I'm not sure if you want all of them, but figured it's easier to add them all in one go and delete what you don't like!

**Comment by ballzy** [comment]
I have cleared my cache but the Evergreen favicon is still appearing in my browser. None of the files in the huge favicon list link to anything either. Wondering if that is the issue

**Comment by ballzy** [comment]
![favicon](https://user-images.githubusercontent.com/4947363/27287388-613c78d8-54fb-11e7-90ff-572a96a77dce.jpg)

**Comment by ballzy** [comment]
Doesn't appear fixed to me

**Comment by Seahermit** [comment]
Think there was a problem with the upload, it's fixed in the source!
