### ISSUE TITLE
HIGH PRIORITY: NHS Logo - new tab should not open

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#51]
Remove link to NHS logo **OR** keep link but don't open a new tab. 
Stewart to confirm

**Comment by Saf456** [comment]
@dogtanian28 please confirm which option is needed and then assign to Ben

**Comment by dogtanian28** [comment]
i think looking at NHS.uk that it should be a link but opening on same screen rather a new tab

**Comment by Seahermit** [comment]
The NHS Logo now links to https://www.nhs.uk in the same page - is that the correct URL? Very easy to change if not

**Comment by Saf456** [comment]
I am happy that this works. To close tomorrow following session with Stewart

**Comment by ballzy** [comment]
@gordonss why did you reopen it? It works as requested doesn't it?

**Comment by ballzy** [comment]
considered done
