### ISSUE TITLE
HIGH PRIORITY: Settings menu is bouncy

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#58]
This is an odd one! During review today we were trying to access the list of options under 'Settings' but the menu kept bouncing. We were using chrome - could be a version issue not sure but needs looking at as it prevents user from choosing an option

**Comment by Seahermit** [comment]
I've been trying to work this one out for quite a while now - it's bouncing as you've hovered over the link, so it starts to open, but then you've left, so it then wants to close, but then you've gone over the link again - do that a few times, and it looks like it's bouncing, when in reality it's just trying to catch up!  Going to try and fiddle with some JQuery stop and clearQueue commands.

**Comment by dogtanian28** [comment]
not sure how to test this as i was never getting the issue in the first place. @Saf456 is this one you can try and replicate to see if it is fixed as you had the issue originally

**Comment by Saf456** [comment]
tested on my laptop with IE and Chrome - no more bounce.
