### ISSUE TITLE
HIGH PRIORITY: Email address verification from EGL

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#61]
Likely content changes needed in this email. This will be reviewed tomorrow.

**Comment by Saf456** [comment]
[Email Address Verification.pdf](https://github.com/AscentMS/NHSD/files/1135011/Email.Address.Verification.pdf)

Email template - Ben will this format work for all the other emails sent out by EGL?

**Comment by Seahermit** [comment]
Yes, that template is fine, the signup email is done, Forgotten is in progress
