### ISSUE TITLE
egl products appearing on contact us page drop down 

### ISSUE THREAD

**Issue by dogtanian28** [AscentMS/NHSD#62]
![image](https://user-images.githubusercontent.com/29567457/27917964-747e8e82-6265-11e7-9e86-c63841633ab2.png)

the above image shows that the "i am using" drop down seems to be appearing sporadically. has been seen on a number of machines. 

also on this page the text in the browser tab is still saying  Evergreen life.

**Comment by ballzy** [comment]
@dogtanian28 are you happy to close this issue?

**Comment by dogtanian28** [comment]
checked in IE, Edge and Chome and now looks ok, so closing as PO
