### ISSUE TITLE
Password reset email refers to Evergreen Life PHR

### ISSUE THREAD

**Issue by gordonss** [AscentMS/NHSD#63]
Password-reset email has this content, which has three issues:
- Email title is 'Your Evergreen Life Temporary Password'
- Main email text includes 'Evergreen Life Personal Health Record in intro
- Link to help is https://e-life.co.uk/Contact hence sends user to main EGL help content
The text is below for info
Hello, 
You've asked us to reset your password for your Evergreen Life Personal Health Record. 
Here is your temporary password 1111, this will be valid for the next 20 minutes. 
If you would like to contact us, please contact us at: e-life.co.uk/Contact 
Thank you, 
The Evergreen Life Team 
People Powered Health

**Comment by ballzy** [comment]
![egl](https://user-images.githubusercontent.com/4947363/27952778-6a60c81a-6301-11e7-8d40-b418a310caa2.jpg)

**Comment by ballzy** [comment]
@Saf456 have you sent over the new content to Ben?

**Comment by Saf456** [comment]
@ballzy see issue on verification email - can use similar content?

**Comment by Saf456** [comment]
@Seahermit  please change EGL references to GP Online Services and replace with the new URL (once we have it)

**Comment by Saf456** [comment]
From	Subject	Received	Size	Categories	
no-reply-test@evergreen-life.co.uk	Your GP Online Services Temporary Password	11:09	21 KB

**Comment by Saf456** [comment]
Hello, 
You've asked us to reset your password for your GP Online Services account. 
Here is your temporary password 2304, this will be valid for the next 24 hours. 
If you would like to contact us, please contact us at: https://gpo.service.nhs.uk/Contact 
Thank you, 
The GP Online Services Team

**Comment by Saf456** [comment]
works!
