### ISSUE TITLE
Password reset screen has some misaligned text fields

### ISSUE THREAD

**Issue by gordonss** [AscentMS/NHSD#64]
Password reset screen has some misaligned text fields, see attached screenshot
![pwdresetissue](https://user-images.githubusercontent.com/9844165/27929063-660adc60-6289-11e7-8208-9284a629344d.png)

**Comment by ballzy** [comment]
I don't get that issue. Which browser? @gordonss

**Comment by gordonss** [comment]
I am using Firefox, 45.4.0

**Comment by ballzy** [comment]
I've just downloaded Firefox and I can't recreate this issue. Best speak when we're both in the office next @gordonss

**Comment by ballzy** [comment]
I might be able to fix it on your computer and work out what the problem could be

**Comment by gordonss** [comment]
OK yep. Monday then?

**Comment by ballzy** [comment]
@Seahermit could you overwrite a previous css style I sent your way with:
div#TablePassword.account { width: 67% }

**Comment by Seahermit** [comment]
Yep, will do
