### ISSUE TITLE
Forgotten password screen allows empty email address form submit

### ISSUE THREAD

**Issue by gordonss** [AscentMS/NHSD#65]
From login, choose 'Forgotten your login details?'
On Password Reset screen (Step 1 of 4), accept the Captcha
Then without entering an email address, choose the submit (Reset Password) button
The form submits and a blank web page is returned

**Comment by ballzy** [comment]
@Seahermit I'm assuming that this is an issue on your original EGL system as well? Can you put some mandatory validation on this please?

**Comment by Seahermit** [comment]
Yep - I'm now typing a snarky message who broke that bit by commenting out the perfectly functioning validity check!  Validity check uncommented, our internal testing also notified, as that seems to have slipped through the cracks!

Good spot!

**Comment by ballzy** [comment]
Hehe - what does the snarky message say? ;)
