### ISSUE TITLE
Contact us page allows many fields to be blank

### ISSUE THREAD

**Issue by gordonss** [AscentMS/NHSD#68]
On the contact page - https://nhs.e-life.co.uk/Contact
Choose values for 'I would like to' and 'This is in relation to', but leave the rest blank
submit the form

The submit is made and the resulting page does not correctly render
By contrast, leave all fields blank (including first two dropdowns) and submit. The page is rendered with missing fields highlighted

**Comment by ballzy** [comment]
Interesting. I'm assuming Evergreen has the same issue. 
The validation on al but the first 2 fields is only cosmetic. Is this possible to fix @Seahermit ?

**Comment by Seahermit** [comment]
Oops, my bad - nest boolean logic!  Was only validating those last boxes when in EGL mode :(

Fixed now...
