### ISSUE TITLE
Contact page message field has no maximum length

### ISSUE THREAD

**Issue by gordonss** [AscentMS/NHSD#69]
On Contact page - https://nhs.e-life.co.uk/Contact
The message TextField does not seem to have a MAXLENGTH on the client side, which used to be best practice - maybe things have moved on since then!

**Comment by ballzy** [comment]
@Seahermit can you elaborate?

**Comment by Seahermit** [comment]
Er, we didn't feel it really needed one - it can be lots, as it goes into an email which then goes into Freshdesk, so didn't bother adding this.  I think it's about 4MB from memory, so lots...  If it's felt to be important, I can add it in!

**Comment by ballzy** [comment]
It's not an issue so long as it is not abused by a BOT to crash the system - Is that a possibility? @gordonss @Seahermit

**Comment by Seahermit** [comment]
It won't crash, it'll just return you to an error page, and that field won't do anything to stop a bot posting directly. I guess they could try and ddos us, but the AWS bits would kick in for that, and setting that size limit wouldn't help in that regard!

It's more from a users point of view - anyone nefarious would just ignore it anyway, and there's only so much anyone will realistically type.

**Comment by Saf456** [comment]
PO happy to leave as is
