### ISSUE TITLE
No navigation out of signup page

### ISSUE THREAD

**Issue by gordonss** [AscentMS/NHSD#70]
Signup page - https://nhs.e-life.co.uk/Signup
This has no 'cancel' or 'take me back' option. Only the form submit.
Actually, there is a 'Login' item at the bottom. Hmm, maybe just semantics, but I do like a good old-fashioned 'cancel' button ;)

**Comment by ballzy** [comment]
I dunno. I'm assuming that it's n EGL decision to try to increase uptake

**Comment by Seahermit** [comment]
Weren't me.  Was a design decision, so @ballzy you are likely correct

**Comment by ballzy** [comment]
OK - maybe it was me. However, I don't see much of an issue here. We're dealing with 100 MAX users and we'll be lucky to get that many so making it slightly more difficult to leave the sign up transaction is to our advantage.\
@dogtanian28 your call

**Comment by dogtanian28** [comment]
happy that the browsers native functionality would be able to deal with this, so will close
