### ISSUE TITLE
Login page says 'New User' button, but page says 'Create Account'

### ISSUE THREAD

**Issue by gordonss** [AscentMS/NHSD#71]
From login - https://nhs.e-life.co.uk/Login
Choose 'New User'. But the screen I end up at is titled 'Create Account', which jars a little

**Comment by ballzy** [comment]
I think it's ok. @dogtanian28 ?

**Comment by Saf456** [comment]
its not a show stopper but having looked at other websites it should say 'Create account for a new user' or equivalent? I will let Stewart make the call on whether this is needed @dogtanian28

**Comment by dogtanian28** [comment]
i think this is fine, as text on the login screen, states "If this is your first time, click NEW USER to create an account." so connects the two.
