### ISSUE TITLE
Signup page says 'surname'

### ISSUE THREAD

**Issue by gordonss** [AscentMS/NHSD#73]
signup page - https://nhs.e-life.co.uk/Signup

Picky, but I thought we try to use the term 'family name' instead of surname. In some cultures, surname is the chosen name, hence the term is not clear

**Comment by ballzy** [comment]
Is this a quick change @Seahermit ?

Could you change "surname" to "Family name" on the create account page

**Comment by ballzy** [comment]
Thank ben
