### ISSUE TITLE
Created appointments are disappearing from the Patients [My Appointments] page.

### ISSUE THREAD

**Issue by andrewleponis** [AscentMS/NHSD#80]
Created appointments are disappearing from the Patients [My Appointments] page.  When the patient tries to rebook the appointment the previously selected slot is now marked as busy and the patient can't reselect it

**Comment by Seahermit** [comment]
If this is with a user linked against the Test01 Practice, this is essentially an artefact of the test service I wrote, as it's not foolproof...

The Currently Booked appointments and Available Appointments are both governed by the Clinical Server, and we don't filter or block any of them in any way - we haven't found an issue with this in the live environment, nor with any of our internal testing (apart from if you're using the Internal Test Clinical Service) so I'm fairly confident it's not really a proper issue...

**Comment by dogtanian28** [comment]
ben thanks for the updated. this is what i thought it could be. 

maybe we can gvie andrew access to the test gp as mentioned last week to confirm

**Comment by Saf456** [comment]
works ok - tested
