### ISSUE TITLE
Sort by Date on Consultation page is inversed

### ISSUE THREAD

**Issue by andrewleponis** [AscentMS/NHSD#81]
As per the image attached, the Order by descriptions (or actual order by) are the wrong way round on Consultation Page.

Consultations are ordered by Date Descending by default.
![ordering issue](https://user-images.githubusercontent.com/29251985/28073715-847d2194-664e-11e7-8cfb-1a3ccb1b6d34.png)

**Comment by dogtanian28** [comment]
Ben,

this looks correct now for descending, i notice though that the icon does not change when you hover over, so they do not look clickable, although they actually are

**Comment by Saf456** [comment]
@Seahermit will you be changing the icon?

**Comment by Seahermit** [comment]
Didn't have a clue what this was about until I fixed something else and realised - the mouse cursor?  If so, that's updated, and I've underlined the links to make them more obvious too.
