### ISSUE TITLE
EGL Logo looks broken on IE 11

### ISSUE THREAD

**Issue by gordonss** [AscentMS/NHSD#82]
IE 11.0.9600 - the Evergreen logo at the bottom as some issue with the white box, see attached
![logoissue](https://user-images.githubusercontent.com/9844165/28118160-f5b54e4a-6707-11e7-92ca-53ae082650d8.png)

**Comment by Seahermit** [comment]
Yay.  IE.  Fixed in next version...

**Comment by Saf456** [comment]
happy looks correct on IE
