### ISSUE TITLE
Scrambled email address and locked out of GP -online

### ISSUE THREAD

**Issue by andrewleponis** [AscentMS/NHSD#83]
Somehow, after testing the re-set Email address I have managed to make my email address not recognised by GP-online.  

I got this warning:
![image](https://user-images.githubusercontent.com/29251985/28156298-0ca9d2ea-67aa-11e7-9a6a-0002e42c3c21.png)

Followed by this message when i try to retrieve my forgotten details: 
![image](https://user-images.githubusercontent.com/29251985/28156364-57706a14-67aa-11e7-83f0-10a003b682f1.png)

**Comment by Seahermit** [comment]
That email address went straight in for me - it didn't get auto completed and include a space on the end perhaps?  I've been meaning to remove trailing whitespace just in case of this

**Comment by dogtanian28** [comment]
sounds like a one off, so i think we will close
