### ISSUE TITLE
GP My Address details - Will accept unlimited Charaters etc

### ISSUE THREAD

**Issue by andrewleponis** [AscentMS/NHSD#85]
All the text boxes accept unlimited text.
where a number should only be possible text character are accepted.  The warning is only displayed after the user clicks save.

![image](https://user-images.githubusercontent.com/29251985/28161897-341b8798-67bd-11e7-9540-75de3d880e87.png)

**Comment by Saf456** [comment]
Part of core EGL product - low issue for pilot

**Comment by Saf456** [comment]
closed with stewat
