### ISSUE TITLE
My GP - More information button not working in some instances

### ISSUE THREAD

**Issue by andrewleponis** [AscentMS/NHSD#86]
1. Click on Settings|My GP
2. Click Edit (see Image)
![image](https://user-images.githubusercontent.com/29251985/28162255-579881ac-67be-11e7-947d-ffe1849f2fe4.png)

3. Click Cancel on My GP: Address details.

4 now try and view More information and this button no longer works
![image](https://user-images.githubusercontent.com/29251985/28162387-bda3e400-67be-11e7-86c1-2bd3b559ac9c.png)

**Comment by Saf456** [comment]
@dogtanian28  tested and replicated in IE11

**Comment by Seahermit** [comment]
Wow.  That is a very specific find!  I shall point out to our testing team that they missed this one (it's the same on our current live site).

Fixed now though!

Good find

**Comment by Saf456** [comment]
tested works fine
