### ISSUE TITLE
Menu Bar enabled immediately after login despite terms of use asking for acceptance or cancalation

### ISSUE THREAD

**Issue by andrewleponis** [AscentMS/NHSD#87]
Surely this should be disabled until the terms and conditions are confirmed?

![image](https://user-images.githubusercontent.com/29251985/28162821-59be62e2-67c0-11e7-8550-945152305770.png)

**Comment by Saf456** [comment]
Thats ok - you should be able to book appointments and prescriptions just not access your record. 
we have tested this
