### ISSUE TITLE
Changing email address email sends Evergreen branded email

### ISSUE THREAD

**Issue by andrewleponis** [AscentMS/NHSD#88]
Security code email (when changing password and email address) is Evergreen branded

**Comment by Saf456** [comment]
is this the same as password re-set email?

**Comment by Seahermit** [comment]
No - there are two different emails - Password Reset and then Email Verification.  Email Verification should be NHS branded, but it sounds like @andrewleponis isn't seeing this?

**Comment by andrewleponis** [comment]
Hi Saf,  this is the message I am getting.  I will re-test today and check I am getting the same result.

![image](https://user-images.githubusercontent.com/29251985/28203161-6b182bbc-6870-11e7-9ce4-187a549fe7cc.png)

**Comment by andrewleponis** [comment]
I have re-test and I am now getting the NHS branded email

**Comment by Saf456** [comment]
The email is a replica of the verification email and not the one above. This need fixing please.

**Comment by Seahermit** [comment]
I've checked this, and email change sends an NHS branded email.  Password reset is a different issue, which I am still working on - that's in Issue #63

**Comment by Saf456** [comment]
NHS branded email
