### ISSUE TITLE
[Changing Security Question] - First attempt 

### ISSUE THREAD

**Issue by andrewleponis** [AscentMS/NHSD#92]
When clicking and trying to remove your very first [Security Question] you get this logon message instead.
Once you have messed around a bit the message never re-appears.

![image](https://user-images.githubusercontent.com/29251985/28205924-09d9becc-687c-11e7-97f9-5a3a38e6a5a8.png)

**Comment by andrewleponis** [comment]
Further to my notes above.  After logging out and back in, I am getting the above message every time I press the [Change Security Question] now and on every Click of [Remove] security Question and [Cancel]

**Comment by Saf456** [comment]
cannot replicate in my account

**Comment by Saf456** [comment]
@Seahermit happy for you to close this if you cannot replicate as well. You may know whats causing it, leave it with you

**Comment by Seahermit** [comment]
I've rebuild the security question changing section to avoid some issues with dynamic controls, so I think this should be fixed - although we've never managed to replicate anything like that in any of our testing!

I'm more confident in the security question updates now, so if this does happen again, I'd be interested to see it!

**Comment by Saf456** [comment]
cannot replicate
