### ISSUE TITLE
Content for 'Ctrl S' download functionality

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#97]
[Print Download Page Ctrl S.pdf](https://github.com/AscentMS/NHSD/files/1155954/Print.Download.Page.Ctrl.S.pdf)

**Comment by Saf456** [comment]
@dogtanian28  we don't need this now do we?

**Comment by Seahermit** [comment]
I don't think you do!

**Comment by dogtanian28** [comment]
looks amazing thanks ben

**Comment by dogtanian28** [comment]
issue can be closed :-)

**Comment by dogtanian28** [comment]
Ben,

one of my colleagues noticed that images weren't downloading, is this just a browser thing?

**Comment by Saf456** [comment]
@dogtanian28  which image?

**Comment by Saf456** [comment]
Was this the NHS logo on the download? If so it is resolved
