### ISSUE TITLE
HIGH: The download journey is not complete and needs to follow through

### ISSUE THREAD

**Issue by Saf456** [AscentMS/NHSD#98]
If you are on a journey to download your medical record, you can click print/download but then there are no further options for download. this is confusing for someone who only wants to download their record.

![image](https://user-images.githubusercontent.com/29437292/28326482-cc3e1530-6bd8-11e7-9b89-3651bcb61642.png)

This is the same on all pages

**Comment by Seahermit** [comment]
I've made a fair bit of progress on this - I've added an extra link beside the Print page, which causes the browser to download a stripped down version of the record.  Depending on the browser, it will either drop it straight to downloads, or pop open the save dialogue, or pop up the invisible yellow bar at the bottom of the window.

And then a message pops up in the middle of the screen telling you this has happened.

Need to add some inline styling to the downloaded record, and probably the NHS logo, but it's working pretty well I think.

**Comment by Saf456** [comment]
Tested this, it does work well. @dogtanian28

**Comment by Saf456** [comment]
@ballzy  could you check the styling.

**Comment by Saf456** [comment]
@Seahermit  download doesn't look like the small download image above. Assume you will be changing?

**Comment by Seahermit** [comment]
The icon you click?  Yes, that will be changing in the next update (probably tonight or tomorrow morning)

**Comment by Seahermit** [comment]
Icon updates, page styling moved inline to download with the file, NHS logo moved to data url to be self-contained within the downloaded file

**Comment by dogtanian28** [comment]
have reviewed bens changes. looks great now, so i think this issue can be closed.

**Comment by Saf456** [comment]
excellent looks good!!
